### ISSUE TITLE
SOAP errors on war deployment

### ISSUE THREAD

**Issue by Gregory-Harris** [WASdev/ci.docker.websphere-traditional#100]
Container started using:
docker run --name test -h test -p 9043:9043 -p 9443:9443 -d ibmcom/websphere-traditional:profile 

Note that I get the same error deploying the old standard  MQTTJavascript.war

was@test:~$ wsadmin.sh AdminApp installInteractive ./rf-app-admin.war
Realm/Cell Name: <default>
Username: wsadmin
Password: FMINem                                                                                                        java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at com.ibm.wsspi.bootstrap.WSLauncher.launchMain(WSLauncher.java:234)
        at com.ibm.wsspi.bootstrap.WSLauncher.main(WSLauncher.java:101)
        at com.ibm.wsspi.bootstrap.WSLauncher.run(WSLauncher.java:82)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:587)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.eclipse.core.launcher.Main.invokeFramework(Main.java:340)
        at org.eclipse.core.launcher.Main.basicRun(Main.java:282)
        at org.eclipse.core.launcher.Main.run(Main.java:981)
        at com.ibm.wsspi.bootstrap.WSPreLauncher.launchEclipse(WSPreLauncher.java:415)
        at com.ibm.wsspi.bootstrap.WSPreLauncher.main(WSPreLauncher.java:176)
Caused by: java.lang.reflect.UndeclaredThrowableException
        at com.sun.proxy.$Proxy7.getAttribute(Unknown Source)
        at com.ibm.ws.management.AdminClientImpl.getAttribute(AdminClientImpl.java:153)
        at com.ibm.ws.scripting.CommonScriptingObject.connectToAdminService(CommonScriptingObject.java:130)
        at com.ibm.ws.scripting.CommonScriptingObject.<init>(CommonScriptingObject.java:104)
        at com.ibm.ws.scripting.AdminControlClient.<init>(AdminControlClient.java:170)
        at com.ibm.ws.scripting.AbstractShell.createControlClient(AbstractShell.java:1366)
        at com.ibm.ws.scripting.AbstractShell.run(AbstractShell.java:2359)
        at com.ibm.ws.scripting.WasxShell.main(WasxShell.java:1256)
        ... 26 more
Caused by: [SOAPException: faultCode=SOAP-ENV:ServerException; msg=The Soap RPC call can&apos;t be unmarshalled.]
        at com.ibm.ws.management.connector.soap.SOAPConnectorClient.handleAdminFault(SOAPConnectorClient.java:969)
        at com.ibm.ws.management.connector.soap.SOAPConnectorClient.invokeTemplateOnce(SOAPConnectorClient.java:934)
        at com.ibm.ws.management.connector.soap.SOAPConnectorClient.invokeTemplate(SOAPConnectorClient.java:699)
        at com.ibm.ws.management.connector.soap.SOAPConnectorClient.invokeTemplate(SOAPConnectorClient.java:689)
        at com.ibm.ws.management.connector.soap.SOAPConnectorClient.getAttribute(SOAPConnectorClient.java:644)
        at com.ibm.ws.management.connector.soap.SOAPConnectorClient.invoke(SOAPConnectorClient.java:500)
        ... 34 more

**Comment by arturdzm** [comment]
Yes, this error usually shows up when password is incorrect.
If you have changed password and running any scripts before start_server executes make sure  
to call /work/modify_password before that.

**Comment by arthurdm** [comment]
@Gregory-Harris - did you get a chance to try the suggested actions?

**Comment by arturdzm** [comment]
Closing for now. Re-open if needed.
